In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [4]:
print(X.shape)
print(X[0])
print(y[0])

(150, 4)
[5.1 3.5 1.4 0.2]
0


In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_trian, y_test = train_test_split(X, y)

### sklearn中的standardScaler

In [25]:
from sklearn.preprocessing import StandardScaler
standardScalar = StandardScaler()

In [26]:
standardScalar.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [27]:
standardScalar.mean_

array([5.82321429, 3.05267857, 3.70089286, 1.19821429])

In [28]:
standardScalar.scale_  #数据分布范围，标准差

array([0.81097188, 0.43588166, 1.74890249, 0.78216528])

In [29]:
X_train_standarded = standardScalar.transform(X_train)

In [30]:
X_train_standarded

array([[-1.50833133e+00,  1.08564852e-01, -1.25844229e+00,
        -1.27621912e+00],
       [-1.50833133e+00,  1.25566518e+00, -1.54433588e+00,
        -1.27621912e+00],
       [ 1.69769847e+00, -1.20855213e-01,  1.20024253e+00,
         5.13683903e-01],
       [ 3.41301249e-01, -5.79695344e-01,  5.71276643e-01,
         2.28303957e-03],
       [-2.86252661e-02, -8.09115410e-01,  7.99991510e-01,
         8.97234551e-01],
       [ 8.34536603e-01,  3.37984918e-01,  7.99991510e-01,
         1.02508477e+00],
       [ 2.31424267e+00, -1.20855213e-01,  1.37177868e+00,
         1.40863542e+00],
       [-1.01509597e+00,  3.37984918e-01, -1.42997844e+00,
        -1.27621912e+00],
       [ 1.20446312e+00,  3.37984918e-01,  1.25742124e+00,
         1.40863542e+00],
       [-2.75242943e-01, -5.79695344e-01,  6.85634076e-01,
         1.02508477e+00],
       [-2.86252661e-02, -8.09115410e-01,  7.99991510e-01,
         8.97234551e-01],
       [ 1.57438963e+00, -1.20855213e-01,  1.25742124e+00,
      

In [31]:
X_test_standard = standardScalar.transform(X_test)

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn_clf = KNeighborsClassifier(n_neighbors=3, n_jobs=-1)

In [34]:
knn_clf.fit(X_train_standarded, y_trian)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=3, p=2,
           weights='uniform')

In [35]:
knn_clf.score(X_test, y_test)

0.3684210526315789

In [36]:
knn_clf.score(X_test_standard, y_test)

0.9210526315789473

可以看出归一化影响很大